// Code generated by ent, DO NOT EDIT.

package job

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the job type in the database.
	Label = "job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldCompany holds the string denoting the company field in the database.
	FieldCompany = "company"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldSalary holds the string denoting the salary field in the database.
	FieldSalary = "salary"
	// FieldEmploymentType holds the string denoting the employment_type field in the database.
	FieldEmploymentType = "employment_type"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPostedOn holds the string denoting the posted_on field in the database.
	FieldPostedOn = "posted_on"
	// FieldScrapedAt holds the string denoting the scraped_at field in the database.
	FieldScrapedAt = "scraped_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// Table holds the table name of the job in the database.
	Table = "jobs"
)

// Columns holds all SQL columns for job fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldCompany,
	FieldLocation,
	FieldSalary,
	FieldEmploymentType,
	FieldURL,
	FieldSource,
	FieldDescription,
	FieldPostedOn,
	FieldScrapedAt,
	FieldStatus,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Status defines the type for the "status" enum field.
type Status string

// StatusSaved is the default value of the Status enum.
const DefaultStatus = StatusSaved

// Status values.
const (
	StatusSaved     Status = "saved"
	StatusApplied   Status = "applied"
	StatusInterview Status = "interview"
	StatusOffer     Status = "offer"
	StatusRejected  Status = "rejected"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSaved, StatusApplied, StatusInterview, StatusOffer, StatusRejected:
		return nil
	default:
		return fmt.Errorf("job: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Job queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByCompany orders the results by the company field.
func ByCompany(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompany, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// BySalary orders the results by the salary field.
func BySalary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSalary, opts...).ToFunc()
}

// ByEmploymentType orders the results by the employment_type field.
func ByEmploymentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmploymentType, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPostedOn orders the results by the posted_on field.
func ByPostedOn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostedOn, opts...).ToFunc()
}

// ByScrapedAt orders the results by the scraped_at field.
func ByScrapedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScrapedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}
