// Code generated by ent, DO NOT EDIT.

package job

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/anujpunekar20/carrier/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTitle, v))
}

// Company applies equality check predicate on the "company" field. It's identical to CompanyEQ.
func Company(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCompany, v))
}

// Location applies equality check predicate on the "location" field. It's identical to LocationEQ.
func Location(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLocation, v))
}

// Salary applies equality check predicate on the "salary" field. It's identical to SalaryEQ.
func Salary(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSalary, v))
}

// EmploymentType applies equality check predicate on the "employment_type" field. It's identical to EmploymentTypeEQ.
func EmploymentType(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEmploymentType, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldURL, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSource, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldDescription, v))
}

// PostedOn applies equality check predicate on the "posted_on" field. It's identical to PostedOnEQ.
func PostedOn(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPostedOn, v))
}

// ScrapedAt applies equality check predicate on the "scraped_at" field. It's identical to ScrapedAtEQ.
func ScrapedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldScrapedAt, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldNotes, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldTitle, v))
}

// CompanyEQ applies the EQ predicate on the "company" field.
func CompanyEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCompany, v))
}

// CompanyNEQ applies the NEQ predicate on the "company" field.
func CompanyNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCompany, v))
}

// CompanyIn applies the In predicate on the "company" field.
func CompanyIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCompany, vs...))
}

// CompanyNotIn applies the NotIn predicate on the "company" field.
func CompanyNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCompany, vs...))
}

// CompanyGT applies the GT predicate on the "company" field.
func CompanyGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCompany, v))
}

// CompanyGTE applies the GTE predicate on the "company" field.
func CompanyGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCompany, v))
}

// CompanyLT applies the LT predicate on the "company" field.
func CompanyLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCompany, v))
}

// CompanyLTE applies the LTE predicate on the "company" field.
func CompanyLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCompany, v))
}

// CompanyContains applies the Contains predicate on the "company" field.
func CompanyContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldCompany, v))
}

// CompanyHasPrefix applies the HasPrefix predicate on the "company" field.
func CompanyHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldCompany, v))
}

// CompanyHasSuffix applies the HasSuffix predicate on the "company" field.
func CompanyHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldCompany, v))
}

// CompanyEqualFold applies the EqualFold predicate on the "company" field.
func CompanyEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldCompany, v))
}

// CompanyContainsFold applies the ContainsFold predicate on the "company" field.
func CompanyContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldCompany, v))
}

// LocationEQ applies the EQ predicate on the "location" field.
func LocationEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLocation, v))
}

// LocationNEQ applies the NEQ predicate on the "location" field.
func LocationNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldLocation, v))
}

// LocationIn applies the In predicate on the "location" field.
func LocationIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldLocation, vs...))
}

// LocationNotIn applies the NotIn predicate on the "location" field.
func LocationNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldLocation, vs...))
}

// LocationGT applies the GT predicate on the "location" field.
func LocationGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldLocation, v))
}

// LocationGTE applies the GTE predicate on the "location" field.
func LocationGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldLocation, v))
}

// LocationLT applies the LT predicate on the "location" field.
func LocationLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldLocation, v))
}

// LocationLTE applies the LTE predicate on the "location" field.
func LocationLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldLocation, v))
}

// LocationContains applies the Contains predicate on the "location" field.
func LocationContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldLocation, v))
}

// LocationHasPrefix applies the HasPrefix predicate on the "location" field.
func LocationHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldLocation, v))
}

// LocationHasSuffix applies the HasSuffix predicate on the "location" field.
func LocationHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldLocation, v))
}

// LocationIsNil applies the IsNil predicate on the "location" field.
func LocationIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldLocation))
}

// LocationNotNil applies the NotNil predicate on the "location" field.
func LocationNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldLocation))
}

// LocationEqualFold applies the EqualFold predicate on the "location" field.
func LocationEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldLocation, v))
}

// LocationContainsFold applies the ContainsFold predicate on the "location" field.
func LocationContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldLocation, v))
}

// SalaryEQ applies the EQ predicate on the "salary" field.
func SalaryEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSalary, v))
}

// SalaryNEQ applies the NEQ predicate on the "salary" field.
func SalaryNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldSalary, v))
}

// SalaryIn applies the In predicate on the "salary" field.
func SalaryIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldSalary, vs...))
}

// SalaryNotIn applies the NotIn predicate on the "salary" field.
func SalaryNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldSalary, vs...))
}

// SalaryGT applies the GT predicate on the "salary" field.
func SalaryGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldSalary, v))
}

// SalaryGTE applies the GTE predicate on the "salary" field.
func SalaryGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldSalary, v))
}

// SalaryLT applies the LT predicate on the "salary" field.
func SalaryLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldSalary, v))
}

// SalaryLTE applies the LTE predicate on the "salary" field.
func SalaryLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldSalary, v))
}

// SalaryContains applies the Contains predicate on the "salary" field.
func SalaryContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldSalary, v))
}

// SalaryHasPrefix applies the HasPrefix predicate on the "salary" field.
func SalaryHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldSalary, v))
}

// SalaryHasSuffix applies the HasSuffix predicate on the "salary" field.
func SalaryHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldSalary, v))
}

// SalaryIsNil applies the IsNil predicate on the "salary" field.
func SalaryIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldSalary))
}

// SalaryNotNil applies the NotNil predicate on the "salary" field.
func SalaryNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldSalary))
}

// SalaryEqualFold applies the EqualFold predicate on the "salary" field.
func SalaryEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldSalary, v))
}

// SalaryContainsFold applies the ContainsFold predicate on the "salary" field.
func SalaryContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldSalary, v))
}

// EmploymentTypeEQ applies the EQ predicate on the "employment_type" field.
func EmploymentTypeEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEmploymentType, v))
}

// EmploymentTypeNEQ applies the NEQ predicate on the "employment_type" field.
func EmploymentTypeNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldEmploymentType, v))
}

// EmploymentTypeIn applies the In predicate on the "employment_type" field.
func EmploymentTypeIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldEmploymentType, vs...))
}

// EmploymentTypeNotIn applies the NotIn predicate on the "employment_type" field.
func EmploymentTypeNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldEmploymentType, vs...))
}

// EmploymentTypeGT applies the GT predicate on the "employment_type" field.
func EmploymentTypeGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldEmploymentType, v))
}

// EmploymentTypeGTE applies the GTE predicate on the "employment_type" field.
func EmploymentTypeGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldEmploymentType, v))
}

// EmploymentTypeLT applies the LT predicate on the "employment_type" field.
func EmploymentTypeLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldEmploymentType, v))
}

// EmploymentTypeLTE applies the LTE predicate on the "employment_type" field.
func EmploymentTypeLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldEmploymentType, v))
}

// EmploymentTypeContains applies the Contains predicate on the "employment_type" field.
func EmploymentTypeContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldEmploymentType, v))
}

// EmploymentTypeHasPrefix applies the HasPrefix predicate on the "employment_type" field.
func EmploymentTypeHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldEmploymentType, v))
}

// EmploymentTypeHasSuffix applies the HasSuffix predicate on the "employment_type" field.
func EmploymentTypeHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldEmploymentType, v))
}

// EmploymentTypeIsNil applies the IsNil predicate on the "employment_type" field.
func EmploymentTypeIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldEmploymentType))
}

// EmploymentTypeNotNil applies the NotNil predicate on the "employment_type" field.
func EmploymentTypeNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldEmploymentType))
}

// EmploymentTypeEqualFold applies the EqualFold predicate on the "employment_type" field.
func EmploymentTypeEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldEmploymentType, v))
}

// EmploymentTypeContainsFold applies the ContainsFold predicate on the "employment_type" field.
func EmploymentTypeContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldEmploymentType, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldURL, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldSource, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldDescription, v))
}

// PostedOnEQ applies the EQ predicate on the "posted_on" field.
func PostedOnEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPostedOn, v))
}

// PostedOnNEQ applies the NEQ predicate on the "posted_on" field.
func PostedOnNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldPostedOn, v))
}

// PostedOnIn applies the In predicate on the "posted_on" field.
func PostedOnIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldPostedOn, vs...))
}

// PostedOnNotIn applies the NotIn predicate on the "posted_on" field.
func PostedOnNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldPostedOn, vs...))
}

// PostedOnGT applies the GT predicate on the "posted_on" field.
func PostedOnGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldPostedOn, v))
}

// PostedOnGTE applies the GTE predicate on the "posted_on" field.
func PostedOnGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldPostedOn, v))
}

// PostedOnLT applies the LT predicate on the "posted_on" field.
func PostedOnLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldPostedOn, v))
}

// PostedOnLTE applies the LTE predicate on the "posted_on" field.
func PostedOnLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldPostedOn, v))
}

// PostedOnIsNil applies the IsNil predicate on the "posted_on" field.
func PostedOnIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldPostedOn))
}

// PostedOnNotNil applies the NotNil predicate on the "posted_on" field.
func PostedOnNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldPostedOn))
}

// ScrapedAtEQ applies the EQ predicate on the "scraped_at" field.
func ScrapedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldScrapedAt, v))
}

// ScrapedAtNEQ applies the NEQ predicate on the "scraped_at" field.
func ScrapedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldScrapedAt, v))
}

// ScrapedAtIn applies the In predicate on the "scraped_at" field.
func ScrapedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldScrapedAt, vs...))
}

// ScrapedAtNotIn applies the NotIn predicate on the "scraped_at" field.
func ScrapedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldScrapedAt, vs...))
}

// ScrapedAtGT applies the GT predicate on the "scraped_at" field.
func ScrapedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldScrapedAt, v))
}

// ScrapedAtGTE applies the GTE predicate on the "scraped_at" field.
func ScrapedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldScrapedAt, v))
}

// ScrapedAtLT applies the LT predicate on the "scraped_at" field.
func ScrapedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldScrapedAt, v))
}

// ScrapedAtLTE applies the LTE predicate on the "scraped_at" field.
func ScrapedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldScrapedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStatus, vs...))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldNotes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
