// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "company", Type: field.TypeString},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "salary", Type: field.TypeString, Nullable: true},
		{Name: "employment_type", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "source", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "posted_on", Type: field.TypeTime, Nullable: true},
		{Name: "scraped_at", Type: field.TypeTime},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		JobsTable,
	}
)

func init() {
}
