// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anujpunekar20/carrier/internal/ent/job"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *JobCreate) SetTitle(v string) *JobCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCompany sets the "company" field.
func (_c *JobCreate) SetCompany(v string) *JobCreate {
	_c.mutation.SetCompany(v)
	return _c
}

// SetLocation sets the "location" field.
func (_c *JobCreate) SetLocation(v string) *JobCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_c *JobCreate) SetNillableLocation(v *string) *JobCreate {
	if v != nil {
		_c.SetLocation(*v)
	}
	return _c
}

// SetSalary sets the "salary" field.
func (_c *JobCreate) SetSalary(v string) *JobCreate {
	_c.mutation.SetSalary(v)
	return _c
}

// SetNillableSalary sets the "salary" field if the given value is not nil.
func (_c *JobCreate) SetNillableSalary(v *string) *JobCreate {
	if v != nil {
		_c.SetSalary(*v)
	}
	return _c
}

// SetEmploymentType sets the "employment_type" field.
func (_c *JobCreate) SetEmploymentType(v string) *JobCreate {
	_c.mutation.SetEmploymentType(v)
	return _c
}

// SetNillableEmploymentType sets the "employment_type" field if the given value is not nil.
func (_c *JobCreate) SetNillableEmploymentType(v *string) *JobCreate {
	if v != nil {
		_c.SetEmploymentType(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *JobCreate) SetURL(v string) *JobCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *JobCreate) SetSource(v string) *JobCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *JobCreate) SetDescription(v string) *JobCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *JobCreate) SetNillableDescription(v *string) *JobCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPostedOn sets the "posted_on" field.
func (_c *JobCreate) SetPostedOn(v time.Time) *JobCreate {
	_c.mutation.SetPostedOn(v)
	return _c
}

// SetNillablePostedOn sets the "posted_on" field if the given value is not nil.
func (_c *JobCreate) SetNillablePostedOn(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetPostedOn(*v)
	}
	return _c
}

// SetScrapedAt sets the "scraped_at" field.
func (_c *JobCreate) SetScrapedAt(v time.Time) *JobCreate {
	_c.mutation.SetScrapedAt(v)
	return _c
}

// Mutation returns the JobMutation object of the builder.
func (_c *JobCreate) Mutation() *JobMutation {
	return _c.mutation
}

// Save creates the Job in the database.
func (_c *JobCreate) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Job.title"`)}
	}
	if _, ok := _c.mutation.Company(); !ok {
		return &ValidationError{Name: "company", err: errors.New(`ent: missing required field "Job.company"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Job.url"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Job.source"`)}
	}
	if _, ok := _c.mutation.ScrapedAt(); !ok {
		return &ValidationError{Name: "scraped_at", err: errors.New(`ent: missing required field "Job.scraped_at"`)}
	}
	return nil
}

func (_c *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(job.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Company(); ok {
		_spec.SetField(job.FieldCompany, field.TypeString, value)
		_node.Company = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(job.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Salary(); ok {
		_spec.SetField(job.FieldSalary, field.TypeString, value)
		_node.Salary = value
	}
	if value, ok := _c.mutation.EmploymentType(); ok {
		_spec.SetField(job.FieldEmploymentType, field.TypeString, value)
		_node.EmploymentType = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(job.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(job.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(job.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.PostedOn(); ok {
		_spec.SetField(job.FieldPostedOn, field.TypeTime, value)
		_node.PostedOn = value
	}
	if value, ok := _c.mutation.ScrapedAt(); ok {
		_spec.SetField(job.FieldScrapedAt, field.TypeTime, value)
		_node.ScrapedAt = value
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (_c *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Job, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
