// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/anujpunekar20/carrier/internal/ent/job"
	"github.com/anujpunekar20/carrier/internal/ent/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *JobUpdate) SetTitle(v string) *JobUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *JobUpdate) SetNillableTitle(v *string) *JobUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCompany sets the "company" field.
func (_u *JobUpdate) SetCompany(v string) *JobUpdate {
	_u.mutation.SetCompany(v)
	return _u
}

// SetNillableCompany sets the "company" field if the given value is not nil.
func (_u *JobUpdate) SetNillableCompany(v *string) *JobUpdate {
	if v != nil {
		_u.SetCompany(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *JobUpdate) SetLocation(v string) *JobUpdate {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *JobUpdate) SetNillableLocation(v *string) *JobUpdate {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *JobUpdate) ClearLocation() *JobUpdate {
	_u.mutation.ClearLocation()
	return _u
}

// SetSalary sets the "salary" field.
func (_u *JobUpdate) SetSalary(v string) *JobUpdate {
	_u.mutation.SetSalary(v)
	return _u
}

// SetNillableSalary sets the "salary" field if the given value is not nil.
func (_u *JobUpdate) SetNillableSalary(v *string) *JobUpdate {
	if v != nil {
		_u.SetSalary(*v)
	}
	return _u
}

// ClearSalary clears the value of the "salary" field.
func (_u *JobUpdate) ClearSalary() *JobUpdate {
	_u.mutation.ClearSalary()
	return _u
}

// SetEmploymentType sets the "employment_type" field.
func (_u *JobUpdate) SetEmploymentType(v string) *JobUpdate {
	_u.mutation.SetEmploymentType(v)
	return _u
}

// SetNillableEmploymentType sets the "employment_type" field if the given value is not nil.
func (_u *JobUpdate) SetNillableEmploymentType(v *string) *JobUpdate {
	if v != nil {
		_u.SetEmploymentType(*v)
	}
	return _u
}

// ClearEmploymentType clears the value of the "employment_type" field.
func (_u *JobUpdate) ClearEmploymentType() *JobUpdate {
	_u.mutation.ClearEmploymentType()
	return _u
}

// SetURL sets the "url" field.
func (_u *JobUpdate) SetURL(v string) *JobUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *JobUpdate) SetNillableURL(v *string) *JobUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *JobUpdate) SetSource(v string) *JobUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *JobUpdate) SetNillableSource(v *string) *JobUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *JobUpdate) SetDescription(v string) *JobUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *JobUpdate) SetNillableDescription(v *string) *JobUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *JobUpdate) ClearDescription() *JobUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPostedOn sets the "posted_on" field.
func (_u *JobUpdate) SetPostedOn(v time.Time) *JobUpdate {
	_u.mutation.SetPostedOn(v)
	return _u
}

// SetNillablePostedOn sets the "posted_on" field if the given value is not nil.
func (_u *JobUpdate) SetNillablePostedOn(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetPostedOn(*v)
	}
	return _u
}

// ClearPostedOn clears the value of the "posted_on" field.
func (_u *JobUpdate) ClearPostedOn() *JobUpdate {
	_u.mutation.ClearPostedOn()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *JobUpdate) SetScrapedAt(v time.Time) *JobUpdate {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableScrapedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdate) SetStatus(v job.Status) *JobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStatus(v *job.Status) *JobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *JobUpdate) SetNotes(v string) *JobUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *JobUpdate) SetNillableNotes(v *string) *JobUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *JobUpdate) ClearNotes() *JobUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(job.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Company(); ok {
		_spec.SetField(job.FieldCompany, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(job.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(job.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Salary(); ok {
		_spec.SetField(job.FieldSalary, field.TypeString, value)
	}
	if _u.mutation.SalaryCleared() {
		_spec.ClearField(job.FieldSalary, field.TypeString)
	}
	if value, ok := _u.mutation.EmploymentType(); ok {
		_spec.SetField(job.FieldEmploymentType, field.TypeString, value)
	}
	if _u.mutation.EmploymentTypeCleared() {
		_spec.ClearField(job.FieldEmploymentType, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(job.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(job.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(job.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(job.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PostedOn(); ok {
		_spec.SetField(job.FieldPostedOn, field.TypeTime, value)
	}
	if _u.mutation.PostedOnCleared() {
		_spec.ClearField(job.FieldPostedOn, field.TypeTime)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(job.FieldScrapedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(job.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(job.FieldNotes, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetTitle sets the "title" field.
func (_u *JobUpdateOne) SetTitle(v string) *JobUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableTitle(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCompany sets the "company" field.
func (_u *JobUpdateOne) SetCompany(v string) *JobUpdateOne {
	_u.mutation.SetCompany(v)
	return _u
}

// SetNillableCompany sets the "company" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableCompany(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetCompany(*v)
	}
	return _u
}

// SetLocation sets the "location" field.
func (_u *JobUpdateOne) SetLocation(v string) *JobUpdateOne {
	_u.mutation.SetLocation(v)
	return _u
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableLocation(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetLocation(*v)
	}
	return _u
}

// ClearLocation clears the value of the "location" field.
func (_u *JobUpdateOne) ClearLocation() *JobUpdateOne {
	_u.mutation.ClearLocation()
	return _u
}

// SetSalary sets the "salary" field.
func (_u *JobUpdateOne) SetSalary(v string) *JobUpdateOne {
	_u.mutation.SetSalary(v)
	return _u
}

// SetNillableSalary sets the "salary" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableSalary(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetSalary(*v)
	}
	return _u
}

// ClearSalary clears the value of the "salary" field.
func (_u *JobUpdateOne) ClearSalary() *JobUpdateOne {
	_u.mutation.ClearSalary()
	return _u
}

// SetEmploymentType sets the "employment_type" field.
func (_u *JobUpdateOne) SetEmploymentType(v string) *JobUpdateOne {
	_u.mutation.SetEmploymentType(v)
	return _u
}

// SetNillableEmploymentType sets the "employment_type" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableEmploymentType(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetEmploymentType(*v)
	}
	return _u
}

// ClearEmploymentType clears the value of the "employment_type" field.
func (_u *JobUpdateOne) ClearEmploymentType() *JobUpdateOne {
	_u.mutation.ClearEmploymentType()
	return _u
}

// SetURL sets the "url" field.
func (_u *JobUpdateOne) SetURL(v string) *JobUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableURL(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *JobUpdateOne) SetSource(v string) *JobUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableSource(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *JobUpdateOne) SetDescription(v string) *JobUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableDescription(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *JobUpdateOne) ClearDescription() *JobUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPostedOn sets the "posted_on" field.
func (_u *JobUpdateOne) SetPostedOn(v time.Time) *JobUpdateOne {
	_u.mutation.SetPostedOn(v)
	return _u
}

// SetNillablePostedOn sets the "posted_on" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillablePostedOn(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetPostedOn(*v)
	}
	return _u
}

// ClearPostedOn clears the value of the "posted_on" field.
func (_u *JobUpdateOne) ClearPostedOn() *JobUpdateOne {
	_u.mutation.ClearPostedOn()
	return _u
}

// SetScrapedAt sets the "scraped_at" field.
func (_u *JobUpdateOne) SetScrapedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetScrapedAt(v)
	return _u
}

// SetNillableScrapedAt sets the "scraped_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableScrapedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetScrapedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdateOne) SetStatus(v job.Status) *JobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStatus(v *job.Status) *JobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *JobUpdateOne) SetNotes(v string) *JobUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableNotes(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *JobUpdateOne) ClearNotes() *JobUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(job.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Company(); ok {
		_spec.SetField(job.FieldCompany, field.TypeString, value)
	}
	if value, ok := _u.mutation.Location(); ok {
		_spec.SetField(job.FieldLocation, field.TypeString, value)
	}
	if _u.mutation.LocationCleared() {
		_spec.ClearField(job.FieldLocation, field.TypeString)
	}
	if value, ok := _u.mutation.Salary(); ok {
		_spec.SetField(job.FieldSalary, field.TypeString, value)
	}
	if _u.mutation.SalaryCleared() {
		_spec.ClearField(job.FieldSalary, field.TypeString)
	}
	if value, ok := _u.mutation.EmploymentType(); ok {
		_spec.SetField(job.FieldEmploymentType, field.TypeString, value)
	}
	if _u.mutation.EmploymentTypeCleared() {
		_spec.ClearField(job.FieldEmploymentType, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(job.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(job.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(job.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(job.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PostedOn(); ok {
		_spec.SetField(job.FieldPostedOn, field.TypeTime, value)
	}
	if _u.mutation.PostedOnCleared() {
		_spec.ClearField(job.FieldPostedOn, field.TypeTime)
	}
	if value, ok := _u.mutation.ScrapedAt(); ok {
		_spec.SetField(job.FieldScrapedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(job.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(job.FieldNotes, field.TypeString)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
