// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/anujpunekar20/carrier/internal/ent/job"
	"github.com/anujpunekar20/carrier/internal/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeJob = "Job"
)

// JobMutation represents an operation that mutates the Job nodes in the graph.
type JobMutation struct {
	config
	op              Op
	typ             string
	id              *int
	title           *string
	company         *string
	location        *string
	salary          *string
	employment_type *string
	url             *string
	source          *string
	description     *string
	posted_on       *time.Time
	scraped_at      *time.Time
	status          *job.Status
	notes           *string
	clearedFields   map[string]struct{}
	done            bool
	oldValue        func(context.Context) (*Job, error)
	predicates      []predicate.Job
}

var _ ent.Mutation = (*JobMutation)(nil)

// jobOption allows management of the mutation configuration using functional options.
type jobOption func(*JobMutation)

// newJobMutation creates new mutation for the Job entity.
func newJobMutation(c config, op Op, opts ...jobOption) *JobMutation {
	m := &JobMutation{
		config:        c,
		op:            op,
		typ:           TypeJob,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withJobID sets the ID field of the mutation.
func withJobID(id int) jobOption {
	return func(m *JobMutation) {
		var (
			err   error
			once  sync.Once
			value *Job
		)
		m.oldValue = func(ctx context.Context) (*Job, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Job.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withJob sets the old Job of the mutation.
func withJob(node *Job) jobOption {
	return func(m *JobMutation) {
		m.oldValue = func(context.Context) (*Job, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m JobMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m JobMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *JobMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *JobMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Job.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *JobMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *JobMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *JobMutation) ResetTitle() {
	m.title = nil
}

// SetCompany sets the "company" field.
func (m *JobMutation) SetCompany(s string) {
	m.company = &s
}

// Company returns the value of the "company" field in the mutation.
func (m *JobMutation) Company() (r string, exists bool) {
	v := m.company
	if v == nil {
		return
	}
	return *v, true
}

// OldCompany returns the old "company" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldCompany(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCompany is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCompany requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCompany: %w", err)
	}
	return oldValue.Company, nil
}

// ResetCompany resets all changes to the "company" field.
func (m *JobMutation) ResetCompany() {
	m.company = nil
}

// SetLocation sets the "location" field.
func (m *JobMutation) SetLocation(s string) {
	m.location = &s
}

// Location returns the value of the "location" field in the mutation.
func (m *JobMutation) Location() (r string, exists bool) {
	v := m.location
	if v == nil {
		return
	}
	return *v, true
}

// OldLocation returns the old "location" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldLocation(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLocation is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLocation requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLocation: %w", err)
	}
	return oldValue.Location, nil
}

// ClearLocation clears the value of the "location" field.
func (m *JobMutation) ClearLocation() {
	m.location = nil
	m.clearedFields[job.FieldLocation] = struct{}{}
}

// LocationCleared returns if the "location" field was cleared in this mutation.
func (m *JobMutation) LocationCleared() bool {
	_, ok := m.clearedFields[job.FieldLocation]
	return ok
}

// ResetLocation resets all changes to the "location" field.
func (m *JobMutation) ResetLocation() {
	m.location = nil
	delete(m.clearedFields, job.FieldLocation)
}

// SetSalary sets the "salary" field.
func (m *JobMutation) SetSalary(s string) {
	m.salary = &s
}

// Salary returns the value of the "salary" field in the mutation.
func (m *JobMutation) Salary() (r string, exists bool) {
	v := m.salary
	if v == nil {
		return
	}
	return *v, true
}

// OldSalary returns the old "salary" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldSalary(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSalary is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSalary requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSalary: %w", err)
	}
	return oldValue.Salary, nil
}

// ClearSalary clears the value of the "salary" field.
func (m *JobMutation) ClearSalary() {
	m.salary = nil
	m.clearedFields[job.FieldSalary] = struct{}{}
}

// SalaryCleared returns if the "salary" field was cleared in this mutation.
func (m *JobMutation) SalaryCleared() bool {
	_, ok := m.clearedFields[job.FieldSalary]
	return ok
}

// ResetSalary resets all changes to the "salary" field.
func (m *JobMutation) ResetSalary() {
	m.salary = nil
	delete(m.clearedFields, job.FieldSalary)
}

// SetEmploymentType sets the "employment_type" field.
func (m *JobMutation) SetEmploymentType(s string) {
	m.employment_type = &s
}

// EmploymentType returns the value of the "employment_type" field in the mutation.
func (m *JobMutation) EmploymentType() (r string, exists bool) {
	v := m.employment_type
	if v == nil {
		return
	}
	return *v, true
}

// OldEmploymentType returns the old "employment_type" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldEmploymentType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmploymentType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmploymentType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmploymentType: %w", err)
	}
	return oldValue.EmploymentType, nil
}

// ClearEmploymentType clears the value of the "employment_type" field.
func (m *JobMutation) ClearEmploymentType() {
	m.employment_type = nil
	m.clearedFields[job.FieldEmploymentType] = struct{}{}
}

// EmploymentTypeCleared returns if the "employment_type" field was cleared in this mutation.
func (m *JobMutation) EmploymentTypeCleared() bool {
	_, ok := m.clearedFields[job.FieldEmploymentType]
	return ok
}

// ResetEmploymentType resets all changes to the "employment_type" field.
func (m *JobMutation) ResetEmploymentType() {
	m.employment_type = nil
	delete(m.clearedFields, job.FieldEmploymentType)
}

// SetURL sets the "url" field.
func (m *JobMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *JobMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *JobMutation) ResetURL() {
	m.url = nil
}

// SetSource sets the "source" field.
func (m *JobMutation) SetSource(s string) {
	m.source = &s
}

// Source returns the value of the "source" field in the mutation.
func (m *JobMutation) Source() (r string, exists bool) {
	v := m.source
	if v == nil {
		return
	}
	return *v, true
}

// OldSource returns the old "source" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldSource(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSource is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSource requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSource: %w", err)
	}
	return oldValue.Source, nil
}

// ResetSource resets all changes to the "source" field.
func (m *JobMutation) ResetSource() {
	m.source = nil
}

// SetDescription sets the "description" field.
func (m *JobMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *JobMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *JobMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[job.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *JobMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[job.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *JobMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, job.FieldDescription)
}

// SetPostedOn sets the "posted_on" field.
func (m *JobMutation) SetPostedOn(t time.Time) {
	m.posted_on = &t
}

// PostedOn returns the value of the "posted_on" field in the mutation.
func (m *JobMutation) PostedOn() (r time.Time, exists bool) {
	v := m.posted_on
	if v == nil {
		return
	}
	return *v, true
}

// OldPostedOn returns the old "posted_on" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldPostedOn(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPostedOn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPostedOn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPostedOn: %w", err)
	}
	return oldValue.PostedOn, nil
}

// ClearPostedOn clears the value of the "posted_on" field.
func (m *JobMutation) ClearPostedOn() {
	m.posted_on = nil
	m.clearedFields[job.FieldPostedOn] = struct{}{}
}

// PostedOnCleared returns if the "posted_on" field was cleared in this mutation.
func (m *JobMutation) PostedOnCleared() bool {
	_, ok := m.clearedFields[job.FieldPostedOn]
	return ok
}

// ResetPostedOn resets all changes to the "posted_on" field.
func (m *JobMutation) ResetPostedOn() {
	m.posted_on = nil
	delete(m.clearedFields, job.FieldPostedOn)
}

// SetScrapedAt sets the "scraped_at" field.
func (m *JobMutation) SetScrapedAt(t time.Time) {
	m.scraped_at = &t
}

// ScrapedAt returns the value of the "scraped_at" field in the mutation.
func (m *JobMutation) ScrapedAt() (r time.Time, exists bool) {
	v := m.scraped_at
	if v == nil {
		return
	}
	return *v, true
}

// OldScrapedAt returns the old "scraped_at" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldScrapedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldScrapedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldScrapedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldScrapedAt: %w", err)
	}
	return oldValue.ScrapedAt, nil
}

// ResetScrapedAt resets all changes to the "scraped_at" field.
func (m *JobMutation) ResetScrapedAt() {
	m.scraped_at = nil
}

// SetStatus sets the "status" field.
func (m *JobMutation) SetStatus(j job.Status) {
	m.status = &j
}

// Status returns the value of the "status" field in the mutation.
func (m *JobMutation) Status() (r job.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldStatus(ctx context.Context) (v job.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *JobMutation) ResetStatus() {
	m.status = nil
}

// SetNotes sets the "notes" field.
func (m *JobMutation) SetNotes(s string) {
	m.notes = &s
}

// Notes returns the value of the "notes" field in the mutation.
func (m *JobMutation) Notes() (r string, exists bool) {
	v := m.notes
	if v == nil {
		return
	}
	return *v, true
}

// OldNotes returns the old "notes" field's value of the Job entity.
// If the Job object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *JobMutation) OldNotes(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNotes is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNotes requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNotes: %w", err)
	}
	return oldValue.Notes, nil
}

// ClearNotes clears the value of the "notes" field.
func (m *JobMutation) ClearNotes() {
	m.notes = nil
	m.clearedFields[job.FieldNotes] = struct{}{}
}

// NotesCleared returns if the "notes" field was cleared in this mutation.
func (m *JobMutation) NotesCleared() bool {
	_, ok := m.clearedFields[job.FieldNotes]
	return ok
}

// ResetNotes resets all changes to the "notes" field.
func (m *JobMutation) ResetNotes() {
	m.notes = nil
	delete(m.clearedFields, job.FieldNotes)
}

// Where appends a list predicates to the JobMutation builder.
func (m *JobMutation) Where(ps ...predicate.Job) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the JobMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *JobMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Job, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *JobMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *JobMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Job).
func (m *JobMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *JobMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.title != nil {
		fields = append(fields, job.FieldTitle)
	}
	if m.company != nil {
		fields = append(fields, job.FieldCompany)
	}
	if m.location != nil {
		fields = append(fields, job.FieldLocation)
	}
	if m.salary != nil {
		fields = append(fields, job.FieldSalary)
	}
	if m.employment_type != nil {
		fields = append(fields, job.FieldEmploymentType)
	}
	if m.url != nil {
		fields = append(fields, job.FieldURL)
	}
	if m.source != nil {
		fields = append(fields, job.FieldSource)
	}
	if m.description != nil {
		fields = append(fields, job.FieldDescription)
	}
	if m.posted_on != nil {
		fields = append(fields, job.FieldPostedOn)
	}
	if m.scraped_at != nil {
		fields = append(fields, job.FieldScrapedAt)
	}
	if m.status != nil {
		fields = append(fields, job.FieldStatus)
	}
	if m.notes != nil {
		fields = append(fields, job.FieldNotes)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *JobMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case job.FieldTitle:
		return m.Title()
	case job.FieldCompany:
		return m.Company()
	case job.FieldLocation:
		return m.Location()
	case job.FieldSalary:
		return m.Salary()
	case job.FieldEmploymentType:
		return m.EmploymentType()
	case job.FieldURL:
		return m.URL()
	case job.FieldSource:
		return m.Source()
	case job.FieldDescription:
		return m.Description()
	case job.FieldPostedOn:
		return m.PostedOn()
	case job.FieldScrapedAt:
		return m.ScrapedAt()
	case job.FieldStatus:
		return m.Status()
	case job.FieldNotes:
		return m.Notes()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *JobMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case job.FieldTitle:
		return m.OldTitle(ctx)
	case job.FieldCompany:
		return m.OldCompany(ctx)
	case job.FieldLocation:
		return m.OldLocation(ctx)
	case job.FieldSalary:
		return m.OldSalary(ctx)
	case job.FieldEmploymentType:
		return m.OldEmploymentType(ctx)
	case job.FieldURL:
		return m.OldURL(ctx)
	case job.FieldSource:
		return m.OldSource(ctx)
	case job.FieldDescription:
		return m.OldDescription(ctx)
	case job.FieldPostedOn:
		return m.OldPostedOn(ctx)
	case job.FieldScrapedAt:
		return m.OldScrapedAt(ctx)
	case job.FieldStatus:
		return m.OldStatus(ctx)
	case job.FieldNotes:
		return m.OldNotes(ctx)
	}
	return nil, fmt.Errorf("unknown Job field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *JobMutation) SetField(name string, value ent.Value) error {
	switch name {
	case job.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case job.FieldCompany:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCompany(v)
		return nil
	case job.FieldLocation:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLocation(v)
		return nil
	case job.FieldSalary:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSalary(v)
		return nil
	case job.FieldEmploymentType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmploymentType(v)
		return nil
	case job.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case job.FieldSource:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSource(v)
		return nil
	case job.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case job.FieldPostedOn:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPostedOn(v)
		return nil
	case job.FieldScrapedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetScrapedAt(v)
		return nil
	case job.FieldStatus:
		v, ok := value.(job.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case job.FieldNotes:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNotes(v)
		return nil
	}
	return fmt.Errorf("unknown Job field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *JobMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *JobMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *JobMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Job numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *JobMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(job.FieldLocation) {
		fields = append(fields, job.FieldLocation)
	}
	if m.FieldCleared(job.FieldSalary) {
		fields = append(fields, job.FieldSalary)
	}
	if m.FieldCleared(job.FieldEmploymentType) {
		fields = append(fields, job.FieldEmploymentType)
	}
	if m.FieldCleared(job.FieldDescription) {
		fields = append(fields, job.FieldDescription)
	}
	if m.FieldCleared(job.FieldPostedOn) {
		fields = append(fields, job.FieldPostedOn)
	}
	if m.FieldCleared(job.FieldNotes) {
		fields = append(fields, job.FieldNotes)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *JobMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *JobMutation) ClearField(name string) error {
	switch name {
	case job.FieldLocation:
		m.ClearLocation()
		return nil
	case job.FieldSalary:
		m.ClearSalary()
		return nil
	case job.FieldEmploymentType:
		m.ClearEmploymentType()
		return nil
	case job.FieldDescription:
		m.ClearDescription()
		return nil
	case job.FieldPostedOn:
		m.ClearPostedOn()
		return nil
	case job.FieldNotes:
		m.ClearNotes()
		return nil
	}
	return fmt.Errorf("unknown Job nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *JobMutation) ResetField(name string) error {
	switch name {
	case job.FieldTitle:
		m.ResetTitle()
		return nil
	case job.FieldCompany:
		m.ResetCompany()
		return nil
	case job.FieldLocation:
		m.ResetLocation()
		return nil
	case job.FieldSalary:
		m.ResetSalary()
		return nil
	case job.FieldEmploymentType:
		m.ResetEmploymentType()
		return nil
	case job.FieldURL:
		m.ResetURL()
		return nil
	case job.FieldSource:
		m.ResetSource()
		return nil
	case job.FieldDescription:
		m.ResetDescription()
		return nil
	case job.FieldPostedOn:
		m.ResetPostedOn()
		return nil
	case job.FieldScrapedAt:
		m.ResetScrapedAt()
		return nil
	case job.FieldStatus:
		m.ResetStatus()
		return nil
	case job.FieldNotes:
		m.ResetNotes()
		return nil
	}
	return fmt.Errorf("unknown Job field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *JobMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *JobMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *JobMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *JobMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *JobMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *JobMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *JobMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Job unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *JobMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Job edge %s", name)
}
